spring:
  cloud:
    gateway:
      routes:
        - id: non-blocking-route
          uri: https://httpbin.org
          predicates:
            - Path=/nonblocking/get
          filters:
            - RewritePath=/nonblocking/get, /get
            - name: NonBlockingHeader
        - id: blocking-route
          uri: https://httpbin.org
          predicates:
            - Path=/blocking/get
          filters:
            - RewritePath=/blocking/get, /get
            - name: BlockingHeader

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

test:
  delay: 3